### ISSUE TITLE
运行的时候报错了，说是找不到什么文件

### ISSUE THREAD

**Issue by chenxuuu** [AxisRay/osu-BeatmapAutoLoader#1]
![qq 20171018110517](https://user-images.githubusercontent.com/10357394/31699226-67131db8-b3f4-11e7-9be5-8e7bcb694bbb.png)

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.FileNotFoundException: 未能加载文件或程序集“EasyHook, Version=2.7.4761.0, Culture=neutral, PublicKeyToken=4b580fca19d0b0c5”或它的某一个依赖项。系统找不到指定的文件。
文件名:“EasyHook, Version=2.7.4761.0, Culture=neutral, PublicKeyToken=4b580fca19d0b0c5”
   在 InjectLoader.InjectManager..ctor(Int32 targetProcess)
   在 InjectLoader.InjectMonitor.<EventReg>b__5_0(Int32 pid)
   在 InjectLoader.InjectMonitor.timer_osuDetector_Tick(Object sender, EventArgs e)
   在 System.Windows.Forms.Timer.OnTick(EventArgs e)
   在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

************** 已加载的程序集 **************
mscorlib
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------
InjectLoader
    程序集版本: 1.0.0.0
    Win32 版本: 1.0.0.0
    基本代码: file:///E:/osu/InjectLoader.exe
----------------------------------------
System.Windows.Forms
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Core
    程序集版本: 3.5.0.0
    Win32 版本: 3.5.30729.8833 built by: WinRelRS3
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
    基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------
mscorlib.resources
    程序集版本: 2.0.0.0
    Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
    基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如: 

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

![qq 20171018110653](https://user-images.githubusercontent.com/10357394/31699238-7a3b7f52-b3f4-11e7-9be6-60fdcfc02139.png)

**Comment by AxisRay** [comment]
EasyHook

缺少第三方的库，EasyHook


With kind regards,

------------------------------------------------------------

Ray Lee (??????)

Student

Mobile: +86-17791320367

Office   E-mail: lirui@stu.xidian.edu.cn

Personal E-Mail: rayleesky@outlook.com

------------------------------------------------------------

School of Life Science and Technology,Xidian University


________________________________
发件人: 晨旭 <notifications@github.com>
发送时间: 2017年10月18日 11:07
收件人: AxisRay/osu-BeatmapAutoLoader
抄送: Subscribed
主题: [AxisRay/osu-BeatmapAutoLoader] 运行的时候报错了，说是找不到什么文件 (#1)


[qq 20171018110517]<https://user-images.githubusercontent.com/10357394/31699226-67131db8-b3f4-11e7-9be5-8e7bcb694bbb.png>

[https://user-images.githubusercontent.com/10357394/31699226-67131db8-b3f4-11e7-9be5-8e7bcb694bbb.png]

有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.IO.FileNotFoundException: 未能加载文件或程序集“EasyHook, Version=2.7.4761.0, Culture=neutral, PublicKeyToken=4b580fca19d0b0c5”或它的某一个依赖项。系统找不到指定的文件。
文件名:“EasyHook, Version=2.7.4761.0, Culture=neutral, PublicKeyToken=4b580fca19d0b0c5”
在 InjectLoader.InjectManager..ctor(Int32 targetProcess)
在 InjectLoader.InjectMonitor.b__5_0(Int32 pid)
在 InjectLoader.InjectMonitor.timer_osuDetector_Tick(Object sender, EventArgs e)
在 System.Windows.Forms.Timer.OnTick(EventArgs e)
在 System.Windows.Forms.Timer.TimerNativeWindow.WndProc(Message& m)
在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

警告: 程序集绑定日志记录被关闭。
要启用程序集绑定失败日志记录，请将注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD)设置为 1。
注意: 会有一些与程序集绑定失败日志记录关联的性能损失。
要关闭此功能，请移除注册表值 [HKLM\Software\Microsoft\Fusion!EnableLog]。

************** 已加载的程序集 **************
mscorlib
程序集版本: 2.0.0.0
Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll
InjectLoader
程序集版本: 1.0.0.0
Win32 版本: 1.0.0.0
基本代码: file:///E:/osu/InjectLoader.exe
System.Windows.Forms
程序集版本: 2.0.0.0
Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms/2.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
System
程序集版本: 2.0.0.0
Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System/2.0.0.0__b77a5c561934e089/System.dll
System.Drawing
程序集版本: 2.0.0.0
Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Drawing/2.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
System.Core
程序集版本: 3.5.0.0
Win32 版本: 3.5.30729.8833 built by: WinRelRS3
基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Core/3.5.0.0__b77a5c561934e089/System.Core.dll
System.Windows.Forms.resources
程序集版本: 2.0.0.0
Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
基本代码: file:///C:/WINDOWS/assembly/GAC_MSIL/System.Windows.Forms.resources/2.0.0.0_zh-CHS_b77a5c561934e089/System.Windows.Forms.resources.dll
mscorlib.resources
程序集版本: 2.0.0.0
Win32 版本: 2.0.50727.8825 (WinRelRS3.050727-8800)
基本代码: file:///C:/Windows/Microsoft.NET/Framework/v2.0.50727/mscorlib.dll

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

启用 JIT 调试后，任何无法处理的异常
都将被发送到在此计算机上注册的 JIT 调试器，
而不是由此对话框处理。

[qq 20171018110653]<https://user-images.githubusercontent.com/10357394/31699238-7a3b7f52-b3f4-11e7-9be6-60fdcfc02139.png>

[https://user-images.githubusercontent.com/10357394/31699238-7a3b7f52-b3f4-11e7-9be6-60fdcfc02139.png]

―
